name: Confirm branch name

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
    # 未指定時のデフォルトは[opened, synchronize, reopened]でcloseは指定しないと発動しない
    types:
      # 作成された場合
      - opened
      # ソース(マージ元)ブランチが更新された場合
      - synchronize
      # 一度クローズされたPRが再度開かれた場合
      - reopened
      # クローズされた場合(マージしてクローズされかは `github.event.pull_request.merged`がtrueかで判定できる)
      - closed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resource
        uses: actions/checkout@v3

      - name: Show
        run: |
          echo "github.event_name                        ==>> '${{ github.event_name }}"
          echo "github.event.commits[0].id               ==>> '${{ github.event.commits[0].id }}"
          echo "github.event.commits[0].timestamp        ==>> '${{ github.event.commits[0].timestamp }}"
          echo "github.event.commits[0].message          ==>> '${{ github.event.commits[0].message }}"
          echo "github.event.commits[0].author.name      ==>> '${{ github.event.commits[0].author.name }}"
          echo "github.event.commits[0].committer.name   ==>> '${{ github.event.commits[0].committer.name }}"
          echo "github.event.head_commit.id              ==>> '${{ github.event.head_commit.id }}"
          echo "github.event.head_commit.timestamp       ==>> '${{ github.event.head_commit.timestamp }}"
          echo "github.event.head_commit.message         ==>> '${{ github.event.head_commit.message }}"
          echo "github.event.head_commit.author.name     ==>> '${{ github.event.head_commit.author.name }}"
          echo "github.event.head_commit.committer.name  ==>> '${{ github.event.head_commit.committer.name }}"
          echo "github.event.pull_request.title          ==>> '${{ github.event.pull_request.title }}'"
          echo "github.event.pull_request.head.sha       ==>> '${{ github.event.pull_request.head.sha }}'"
          echo "github.event.pull_request.merged         ==>> '${{ github.event.pull_request.merged }}'"
          echo "github.event.pull_request.labels.*.name  ==>> '${{ github.event.pull_request.labels.*.name }}'"
          echo "github.ref_name                          ==>> '${{ github.ref_name }}'"
          echo "github.head_ref                          ==>> '${{ github.head_ref }}'"
          echo "github.base_ref                          ==>> '${{ github.base_ref }}'"
          echo "git branch --show-current                ==>> '$(git branch --show-current)'"
          echo "GITHUB_REF                               ==>> '${GITHUB_REF}'"
          echo "GITHUB_REF#refs/heads/                   ==>> '${GITHUB_REF#refs/heads/}'"
          echo "GITHUB_HEAD_REF                          ==>> '${GITHUB_HEAD_REF}'"
          echo "GITHUB_BASE_REF                          ==>> '${GITHUB_BASE_REF}'"
          echo "-------------------- git log -1 --format:%s --------------------"
          git log -1 --format=%B
          echo "-------------------- toJson(github.event.push) --------------------"
          echo " '${{ toJson(github.event.push) }}'"
          echo "-------------------- toJson(github.event.pull_request) --------------------"
          echo " '${{ toJson(github.event.pull_request) }}'"
