name: Confirm trigger

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - edited
      - closed
  workflow_dispatch:
    inputs:
      select_item:
        description: "Select the item."
        type: choice
        options:
          - none
          - foo
          - bar
          - baz

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resource
        uses: actions/checkout@v3

      - name: Show
        run: |
          echo "git branch --show-current=$(git branch --show-current)"
          echo "github.event_name=${{ github.event_name }}"
          echo "github.event.pull_request.merged=${{ github.event.pull_request.merged }}"
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REF#refs/heads/=${GITHUB_REF#refs/heads/}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.head_ref=${{ github.head_ref }}"
          echo "github.base_ref=${{ github.base_ref }}"
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "github.event.inputs.select_item=${{ github.event.inputs.select_item }}"
