name: Confirm trigger

on:
  push:
    branches:
      - develop
      - testing
      - production
  pull_request:
    branches:
      - develop
      - testing
      - production
    types:
      - closed
  workflow_dispatch:
    inputs:
      update_level:
        description: "Select increment level."
        type: choice
        options:
          - not_update
          - patch
          - minor
          - major

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resource
        uses: actions/checkout@v3

      - name: Show
        run: |
          echo "github.event_name=${{ github.event_name }}"
          echo "github.event.pull_request.merged=${{ github.event.pull_request.merged }}"
          git branch
          echo "source => ${GITHUB_HEAD_REF}"
          echo "target => ${GITHUB_BASE_REF}"
          echo "${{ toJson(github) }}"
